name: Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  DENO_VERSION: 1.11.3

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Just
        uses: extractions/setup-just@v1
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: just install
        name: Install dependencies
      - run: just lint
        name: Lint
      - run: just test
        name: Unit Tests
        env:
          TEST_PLEX_URL: ${{ secrets.TEST_PLEX_URL }}
          TEST_PLEX_TOKEN: ${{ secrets.TEST_PLEX_TOKEN }}
      - run: just test-e2e
        name: E2E Tests
        # if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
        env:
          TEST_PLEX_URL: ${{ secrets.TEST_PLEX_URL }}
          TEST_PLEX_TOKEN: ${{ secrets.TEST_PLEX_TOKEN }}
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v2
        if: ${{ failure() && (github.event_name == 'pull_request' || github.ref == 'refs/heads/main') }}
        with:
          name: screenshots
          path: ./screenshots
          retention-days: 1
