name: Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Just
        uses: extractions/setup-just@v1
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - run: just install
        name: Install dependencies
      - run: just lint
        name: Lint
      - run: just test
        name: Unit Tests
        env:
          TEST_PLEX_URL: ${{ secrets.TEST_PLEX_URL }}
          TEST_PLEX_TOKEN: ${{ secrets.TEST_PLEX_TOKEN }}
      - run: |
          just build-binary linux-amd64
          just test-e2e linux-amd64
        name: E2E Tests
        env:
          PLEX_URL: ${{ secrets.TEST_PLEX_URL }}
          PLEX_TOKEN: ${{ secrets.TEST_PLEX_TOKEN }}
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: screenshots
          path: ./screenshots
          retention-days: 1
